[line_break]
disabled = true

[directory]
truncation_length = 5
truncation_symbol = 'â€¦/'

[time]
disabled=true
format = 'at [$time]($style) '

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style) '

[docker_context]
format = '[ğŸ‹ $context](blue bold) '

[package]
format = '[$symbol$version]($style) '

[rust]
format = '[$symbol($version)]($style) '
